### ISSUE TITLE
to analyze: `enc_publish` as a way of simplifying the c-bindings for encrypting messages

### ISSUE THREAD

**Issue by richard-ramos** [logos-messaging/logos-delivery-go#641]
### Problem
https://github.com/waku-org/go-waku/pull/635 changes the c-bindings API to use a separate function to encrypt the messages, and then the result of that function can be broadcasted with relay/lightpush publish

### Suggested solution
See discussion: https://github.com/waku-org/go-waku/pull/635#issuecomment-1672623453

**Comment by chair28980** [comment]
Closing as completed per go-waku pm 2023-12-12.
